percona/percona-toolkit

docs/user/README
Added missing docs/user directory where all PT documentation is generated and saved
Perhaps it got lost during transition from Launchpad due to it being empty at the moment and GIT doesn't track empty dirs?
Anyway, added a simple README file to be able to track it from now on.
=> added missing user dir in docs

bin/pt-archiver
Makes --no-delete and --purge options (which are incompatible) mutually exclusive
=> pt-archiver purge and no-delete are mutually exclusive - lp1452914

bin/pt-archiver
pt-archiver was too aggressive checking for slave lag, doing it for every row inserted.
Now it checks every 100 rows. Speed improved substantially.
=> pt-archiver corrected excessively frequent lag check

bin/pt-online-schema-change
Removed ReadKeyMini that caused trouble in some circumstances:
https://bugs.launchpad.net/percona-toolkit/+bug/1450499
Originally included to solve inconsistent terminal state when tool was interrupted during the ask password phase.
https://bugs.launchpad.net/percona-toolkit/+bug/1396870
We now use Term::ReadKey for this. Since this module's availability is not guaranteed, we include it within an eval, and use it's ReadMode function conditional to it having been successfully imported.
=> pt-osc fixed ReadKeyMini issue

bin/pt-sift
pt-sift uses some other tools so it checks if they are present and downloads them using "curl" if missing.
This started to fail once percona.com website protocol changed to https.
Solved changing to http->https and also adding redirect option to curl "-L" for good measure.
=> pt-sift failed to download missing tools

config/deb/control, util/build-packages
Some minor changes in build-packages script to allow building packages from git source tree and also updated info in debian control file for github.
Here's how build looks:
**Build test when there are changes in the tree - staged and non-staged**
vagrant@t-ubuntu1204-64:/vagrant/percona-toolkit/util$ ./build-packages 2.2.14 ../../release_notes.rst                                                                                                                                 
Checking branch... The branch has uncommitted changes or unknown files
**Update files with new version**
vagrant@t-ubuntu1204-64:/vagrant/percona-toolkit/util$ ./build-packages 2.2.15 ../../release_notes.rst
Checking branch... OK
Checking new version 2.2.15... OK
Checking Changelog... OK
Checking release_notes.rst... …
=> Changes needed to build packages from git tree (BLD-271)

bin/pt-kill
The standard way to kill a query in MySQL is to run the command "kill query [thread-id]" and the way to kill a connection is the command "kill [thread-id]". The script pt-kill uses the earlier if you specify --kill-query and the later if you specify --kill in the options.
Unfortunately due to limited privileges, we are not able to run these commands in RDS. RDS provides stored procedure analogous to those two commands for us to use. These procedures run using a system similar to setuid to run the commands as a more privileged user. The procedure for "kill [thread-id]" is "CALL mysql.rds_kill( [thread-id] )" and "CALL mysql.rds_kill_query( [thread-id] )" for "kill query [thread-id]".
http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.MySQL.CommonDBATasks.html
This patch enables …
=> enable support for RDS in pt-kill

bin/pt-stalk
Frank: This adds a simple tokudb_status function copied from the existing innodb_status one, that does not create the files if the client returns an error (as that would imply the engine is unknown to the server). 
I did minimal testing on an instance with and without tokudb and it behaved as expected.
=> added tokudb_status

bin/pt-archiver, lib/OptionParser.pm
Added the the possibility to mark an option as "repeatable" in OptionParser module.
This allows for options to be specified multiple time to create an array, instead of overwriting the previous definition.
This was then used in pt-archiver to be able to define multiple --check-slave-lag options and to check those slaves in a loop. (separating multiple DSNs by a comma was not practical due to regex limitations and the DSN format)
Note that this does not affect previous behaviour of tools because only options marked as "repeatable" are affected, and this was used only in pt-archiver for the --check-slave-lag option, and handled specially for it.
The ability to mark an option as repeatable may be used later on for other options (e.g --set-vars)
=> pt-archiver multple slave lag and OptionParser repeatable option

bin/pt-online-schema-change, t/pt-online-schema-change/rename_fk_constraints.t, t/pt-online-schema-change/samples/bug-1215587.sql
Problem: 
Every time pt-online-schema runs and --alter-foreign-keys-method=rebuild_constraints , the names of the contraints in the new table are prefixed with an underscore (to avoid conflict).
This is done for both the constraints in the altered table and for the constraints in the child tables.
If the tool is run routinely, the name of the constraints can get very long and even exceed the allowed limit.
Solution: 
Change the renaming policy. If the name has no prefixed underscore, add one. If the name already has a prefixed underscore, remove it.
A test was added to test this new behavior
https://bugs.launchpad.net/percona-toolkit/+bug/1215587
=> pt-osc now limits size of contraint names

bin/pt-online-schema-change, t/pt-online-schema-change/basics.t
Background: 
a) The option --chunk-size-limit is meant to put an upper limit to the size of a chunk that pt-osc will copy to the new, altered table. (otherwise it bails)
b) It also plays a role in deciding if a table can be copied in one chunk and if the table in the slave can also be copied in one chunk (otherwise it bails)
Problem:
Setting --chunk-size-limit=0 is supposed to suppress checking for a chunk size limit.
This is true for (a), but it fails in the case of (b) ... i.e , It always bails in the case of a single chunk copy.
Solution:
Simply skip checking chunk size for case (b) if chunk-size-limit=0
Added test case
=> pt-osc chunk-size-limit=0 skips tables - lp1441928

bin/pt-archiver, bin/pt-config-diff, bin/pt-deadlock-logger, bin/pt-duplicate-key-checker, bin/pt-find, bin/pt-fk-error-logger, bin/pt-heartbeat, bin/pt-index-usage, bin/pt-kill, bin/pt-mysql-summary, bin/pt-online-schema-change, bin/pt-query-digest, bin/pt-show-grants, bin/pt-slave-delay, bin/pt-slave-find, bin/pt-slave-restart, bin/pt-stalk, bin/pt-table-checksum, bin/pt-table-sync, bin/pt-table-usage, bin/pt-upgrade, bin/pt-variable-advisor, bin/pt-visual-explain
Doc change in all tools: Specify that commas in passwords must be escaped.
=> DSN doc: need to escape commas in password

bin/pt-archiver
when innodb_kill_idle_transaction is set and waiting for slave lag exceeds that time, pt-archiver bails when slave catches up.
fixed by issuing a "keepalive" dummy query every slave lag check.
=> pt-archiver timeout when waiting for lag

bin/pt-online-schema-change, lib/FlowControlWaiter.pm
Created FlowControlWaiter module and incorporated it to pt-online-schema-changer.
This allows the tool to pause activity when a certain amount of Flow Control activity is detected in a cluster.
Flow Control is the means by which a cluster node can signal others to stop sending transactions until it's own queue falls below a max limit.
When the --max-flow-ctl option is specified (a percentage value) , the tool will periodically check the average amount of Flow Control activity (i.e: average time in FC pause state), and if it is over the provided percentage, tool will pause until that value abates.
=> pt-osc: added PXC Flow Control awareness - lp1413101

bin/pt-archiver, lib/Cxn.pm, lib/FlowControlWaiter.pm
Similar to pt-online-schema-change:
Used FlowControlWaiter module to periodically check for average Flow Control pausing
Activated by option --max-flow-ctl , which receives a float representing the maximum (moving) average of Flow Control allowed before the tool pauses for '--check-interval' seconds (default 1 sec)
Default is no checking for flow control.
=> pt-archiver added flow control awareness for PXC

bin/pt-heartbeat, t/pt-heartbeat/basics.t, t/pt-heartbeat/multi_update_mode.t
problem: if using RBR (default in 5.7) , and master heartbeat table is dropped and later re-created, when trying to "replace" to insert the initial heartbeat row on master, RBR changes "replace" to "insert" in the replication. This breaks replication in the slaves that already have the same row in them.
solution: many "workarounds" failed because of singularities of RBR (replace, delete then insert, insert ignore, insert on duplicate update). 
Finally "truncate table" did the trick.
=> Pt heartbeat requires binlog format statement

bin/pt-table-usage
The "extended" option in the "explain" command is implicit since 5.7.3 and now throws a warning.
Eventually to be deprecated.
Fixed by adding VersionParser module, checking mysql version and removing option if >= 5.7.3
=> pt-table-usage 5.7 compat - EXPLAIN EXTENDED is now implicit

config/rpm/percona-toolkit.spec
The License field in the Percona-toolkit RPM is GPL. This does not tell
the version of GPL and might confuse tools and users that rely on this
field.
Best practice in the RPM world is to use "GPLv2" for the GPL 2.0
license.
The commit switches the license field of the RPM to GPLv2.
=> Fix #1508401 Specify GPL Version in the RPm metadata

bin/pt-online-schema-change, t/pt-online-schema-change/bugs.t, t/pt-online-schema-change/samples/bug-1336734.sql
Problem:
when modifying a column that allows NULL values to one that doesn't, pt-osc fails when copying rows that have a null value assigned, even when the new column has been assigned a DEFAULT.
Although this is probably a good default behavior, it is sometimes desirable for the copied null columns to adopt the new default value.
Solution:
Add an option that adds the related error (1048) to the list of ignored errors.
Note: This has the effect of copying the row, assigning the default value if given, or the inbuilt default value for the datatype, if an explicit DEFAULT value is not given in the --alter; 
e.g: 0 if numeric, empty string for string.
=> pt-osc added --null-to-not-null option

bin/pt-online-schema-change, bin/pt-query-digest, lib/MasterSlave.pm, t/pt-online-schema-change/basics.t, t/pt-online-schema-change/samples/create_dsns.sql
pt-osc recursion-method choked on dsn method.
Customized MasterSlave module was the culprit. Apparently It was customized for pt-osc (and pt-query-digest) and when tools were updated customization was overwritten.
Fixed by modifying the module with the enhancement and applying it to pt-osc (and pt-query-digest)
Created unit test for pt-osc for this.
=> pt-osc fixed recursion method dsn - lp1523685

bin/pt-archiver, bin/pt-config-diff, bin/pt-deadlock-logger, bin/pt-duplicate-key-checker, bin/pt-find, bin/pt-fk-error-logger, bin/pt-heartbeat, bin/pt-index-usage, bin/pt-kill, bin/pt-online-schema-change, bin/pt-query-digest, bin/pt-show-grants, bin/pt-slave-delay, bin/pt-slave-find, bin/pt-slave-restart, bin/pt-table-checksum, bin/pt-table-sync, bin/pt-table-usage, bin/pt-upgrade, bin/pt-variable-advisor, bin/pt-visual-explain, lib/DSNParser.pm, t/pt-online-schema-change/basics.t, t/pt-online-schema-change/bugs.t, t/pt-online-schema-change/samples/sql_mode_issue_lp1506748.sql, t/pt-online-schema-change/samples/stats-execute-5.6.txt, t/pt-table-checksum/progress.t
Problem: what the title says  :-)
original code was:
- read current modes
- set user vars
- set sql_mode=NO_AUTO_VALUE_ON_ZERO + original modes
new code:
- set user vars
- read current modes
- set sql_mode=NO_AUTO_VALUE_ON_ZERO + current modes
Updated all tools. Checked that all of them are aligned. Tested them. Created unit test. Documented usage on pt-osc (arguably the most sensitive to the bug, might need to document on more tools that use --set vars)
=> DSNParser clobbered sql_mode variable set by user - lp1506748

bin/pt-diskstats, bin/pt-fk-error-logger, bin/pt-heartbeat, bin/pt-index-usage, bin/pt-kill, bin/pt-online-schema-change, bin/pt-query-digest, bin/pt-slave-delay, bin/pt-slave-find, bin/pt-table-checksum, bin/pt-table-sync, bin/pt-table-usage, bin/pt-upgrade, lib/Progress.pm, lib/QueryReportFormatter.pm, lib/Transformers.pm, t/pt-query-digest/issue_1186.t, t/pt-slave-restart/pt-slave-restart.t, t/pt-table-checksum/basics.t, t/pt-table-checksum/run_time.t
various fixes related to perl 5.22 
* printf/sprintf now emits a warning if receives more values than described in the format string.
Fixed by adding an index to each format symbol (no warnings are emitted if they have an index)
* The character multiplier function ( e.g: print "=" x $count ) now emits a warning if $count is negative.
* Unrelated to perl but to a CPAN module: GetOpt::Long has a few versions where it doesn't accept float values without the integer part (e.g.  .5 instead of 0.5 )
Just changed the tests in this case.
=> Perl sprintf warnings lp1480719

bin/pt-stalk, lib/bash/collect.sh
The shell "collect" module confused the new mysql var: "binlog_error_action" with "log_error"
https://dev.mysql.com/doc/refman/5.7/en/replication-options-binary-log.html#sysvar_binlog_error_action
Also aligned many module diffs with the one contained in pt-stalk (only tool that uses it)
=> new var binlog_error_action caused bug in collect module

bin/pt-query-digest
clarify the way to disable --attribute-value-limit in the docs
=> pt-qd clarify attribute-value-limit in docs

bin/pt-online-schema-change, t/pt-online-schema-change/bugs.t, t/pt-online-schema-change/samples/simple_test_table.sql
https://bugs.launchpad.net/percona-toolkit/+bug/1526105
Problem:
If you run pt-osc more than 10 times using --no-drop-old-table, the 11th time it fails because it can't find a unique table name.
Solution:
After 10th try, generate a random 6 letter alphanumeric prefix, which virtually guarantees no conflict. (try 10 more times for extra measure)
I considered generating the random prefix at the start but since this is an edge case, and underscores are "friendlier" to look at, I think this is a good compromise.
Created unit test.
=> pt-osc generate random table prefix after 10th try

bin/pt-table-checksum
preface: when the estimated number of rows of a slave table exceeds that of the master table, and the master table has been determined to be done in one whole chunk, the table is skipped.
problem: since the number of rows is often just an estimate, tables get skipped for even minor discrepancies.
solution: add option --slave-skip-tolerance that receives float value. e.g. a value of 1.2 will tolerate a difference of excess 20% rows. Default value is 1.0, so no change to default behavior.
note: possible ideal future solution:  eliminate one chunk checksuming.
=> pt-t-c add --slave-skip-tolerance option

bin/pt-table-sync
documented that pt-table-sync will attempt to set master binlog_format session to statement, and that it needs super privilege for that.
=> pt-table-sync document rbr limitation

bin/pt-query-digest, lib/JSONReportFormatter.pm, lib/QueryReportFormatter.pm, t/pt-query-digest/json.t, t/pt-query-digest/samples/json/slow002-anon_no_vertical.txt, t/pt-query-digest/samples/json/slow002_no_vertical.txt, t/pt-query-digest/samples/slow001_tablesreport_no_vertical.txt, t/pt-query-digest/samples/slow002_report_no_vertical.txt, t/pt-query-digest/slowlog_analyses.t
Adds --no-vertical-format option for pt-query-digest, allowing compatibility with non-standard mysql clients that don't support the "\G" directive at the end of a statement.
Original contribution and pull request submitted by Ivan Zahriev
https://github.com/famzah
=> pt-query-digest - allow no-vertical-format option for mysql clients that don't support it

bin/pt-align, bin/pt-archiver, bin/pt-config-diff, bin/pt-deadlock-logger, bin/pt-diskstats, bin/pt-duplicate-key-checker, bin/pt-fifo-split, bin/pt-find, bin/pt-fingerprint, bin/pt-fk-error-logger, bin/pt-heartbeat, bin/pt-index-usage, bin/pt-kill, bin/pt-online-schema-change, bin/pt-query-digest, bin/pt-show-grants, bin/pt-slave-delay, bin/pt-slave-find, bin/pt-slave-restart, bin/pt-table-checksum, bin/pt-table-sync, bin/pt-table-usage, bin/pt-upgrade, bin/pt-variable-advisor, bin/pt-visual-explain, lib/OptionParser.pm
Perl based tools returned a non zero exit status when issued with the --version option.
Fixed in OptionParser module and updated in all tools.
=> --version returns exit status 1

bin/pt-slave-restart
verbose option documentation in pt-slave-restart might lead to believe it required an integer as a parameter, instead of being a flag.
=> calrified pt-slave-restart --verbose doc

bin/pt-table-checksum, lib/NibbleIterator.pm, t/pt-table-checksum/chunk_index.t
glitch in code sometimes did not allow tool to choose primary key as index when using --where clause.
=> Pt-tcs --where option using non optimal index lp1576036

bin/pt-query-digest, t/lib/samples/genlogs/genlog005.txt, t/pt-query-digest/genlog_analyses.t, t/pt-query-digest/samples/genlog005.txt
MySQL 5.7 general log dates are in RFC3339 format: 2006-01-02T15:04:05Z07:00
The previous version of the log parser was not able to parse this format for general log.
=> BUG-1585412 Fixed Date parsing regex for MySQL 5.7

bin/pt-query-digest, t/pt-query-digest/mysql_analyses.t
changed default attribute-value-limit to disabled, since some values are now exceeding de previous default 4G
e.g. number of rows returned
=> pt-query-digest changed default attribute-value-limit to disabled

bin/pt-archiver, bin/pt-online-schema-change, bin/pt-table-checksum, bin/pt-table-sync, lib/TableNibbler.pm, t/lib/TableNibbler.t, t/pt-archiver/issue_1166.t, t/pt-archiver/issue_1593265.t, t/pt-archiver/samples/issue_1593265.sql
In the case we are trying to migrate a table with no PK nor an unique
key, pt-archiver was failing to select the correct rows for deletion.
This fix implemented here is to add ALL columns in the WHERE clause of
the DELETE command. This way, we are deleting only the exact same row we
just migrated but using columns instead of an index.
=> bug-1593265 Fixed pt-archiver deletes wrong rows

bin/pt-online-schema-change, lib/DSNParser.pm
I have added the --preserve-triggers flag to pt-online-schema-change.
With this flag, pt-osc will preserve and edit triggers that already exist on a table. This has been tested on mysql < 5.7 and in sysbench with concurrency.
This gets rid of one shortcoming with pt-osc in that it cannot work in environments with triggers.
=> Added --preserve-triggers to pt-osc

Changelog, bin/pt-kill
The problem was the script was not cleaning up a structure where it holds the reasons that made the queries to match the rules.
=> Bug-1592166 pt-kill leaks memory each time it kills a query

bin/pt-archiver, bin/pt-heartbeat, bin/pt-kill, bin/pt-online-schema-change, bin/pt-query-digest, bin/pt-slave-find, bin/pt-slave-restart, bin/pt-table-checksum, bin/pt-table-sync, lib/MasterSlave.pm, t/pt-online-schema-change/basics.t
As requested in https://bugs.launchpad.net/percona-toolkit/+bug/1595912 and https://bugs.launchpad.net/percona-toolkit/+bug/1595678 now there are 2 new cli parms ofr pt-osc:  
`--slave-user` and `--slave-password` to be able to have less privileged users on slaves.
=> Bug-1595678 Added --slave-user and --slave-password cli params to pt-osc

bin/pt-heartbeat, t/pt-heartbeat/basics.t
Now it is possible to set a stora engine for the heartbeat table, different than the DB default by using the `--create-table-engine` param.
=> BUG-1517155 Added --create-table-engine param to pt-heartbeat

bin/pt-table-sync, lib/ChangeHandler.pm
My particular use case is that I have an enum value "0x0" which gets caught up in the hexadecimal check in https://github.com/percona/percona-toolkit/blob/2.2/bin/pt-table-sync#L1895 .  When this occurs, pt-table-sync treats the value as a hexadecimal value and bombs out when I get a "Data truncated for column" mysql error on insert/update.
=> add enum column type to is_char check so that values are properly quoted

bin/pt-query-digest, lib/SlowLogParser.pm
https://bugs.launchpad.net/percona-toolkit/+bug/1581752
Time field in slow log in 5.7 has new format:
"Time: 2016-05-14T05:28:50.060335Z"
Thus --since and --until pt-query-digest options producing empty result.
=> fix lp:1581752 5.7 compatibility for pt-query-digest, slow log time format

bin/pt-index-usage, bin/pt-query-digest, bin/pt-table-usage, bin/pt-upgrade, lib/SlowLogParser.pm, t/lib/SlowLogParser.t, t/lib/samples/slowlogs/mysql5.7.log
Tests added for SlowLogParser
SlowLogParser now is able to handle MySQL dates in RFC3339 format.
A new test for this case was added and all scripts using SlowLogParser in bin/ have been updated.
=> BUG-1581752-slow_log

bin/pt-online-schema-change, lib/ReplicaLagWaiter.pm
This is to add/remove monitored machines while the OSC runs.
This contains work by:
- Daniël van Eeden <daniel.vaneeden@booking.com>
- Mikhail Izioumtchenko <mikhail.izioumtchenko@booking.com>
=> Recheck the list of slaves in the table specified with DSN

bin/pt-online-schema-change
Replaced an // with || since // was introduced in Perl 5.10 so it was failing on Perl 5.8.8 (Centos 5)
=> Fixed systax error in Perl 5.8.8

bin/pt-online-schema-change, bin/pt-table-checksum, lib/NibbleIterator.pm, t/pt-online-schema-change/bugs.t, t/pt-online-schema-change/samples/bug-1613915.sql
pt-online-schema-change was failing when the key used has an enum field and elements are not defined in alphabetical order.
Example:
```
enum('FOO','BAR','BAT','BAZ','CAT','DOG','DERP','HERP','VANILLA','CHOCOLATE','MINT')
```
In this case pt-osc's Nibbler fails to calculate the boundaries for each chunk, because `SORT` on `ENUM` fields is calculated by the item index in the definition and not by its value.
Fixed to use `CONCAT(field)` for ENUMs, like described in the documentation.
http://dev.mysql.com/doc/refman/5.6/en/enum.html#enum-sorting
=> Bug 1613915

bin/pt-show-grants
Fix pt-show-grants to run on MariaDB 10.0+
This was happening on 2.2.17:
```
$ sudo pt-show-grants
-- Grants dumped by pt-show-grants
-- Dumped from server Localhost via UNIX socket, MySQL 10.1.11-MariaDB-log at 2016-07-15 15:04:35
Use of uninitialized value $create in substitution (s///) at /usr/bin/pt-show-grants line 1923.
```
=> Fix version check in pt-show-grants for MariaDB 10.0+

bin/pt-slave-restart
background: pt-slave-restart checks for MySQL version and if gtid is enabled to handle skipping in a different way accordingly.
MariaDB uses a different versioning number system so this failed for that database.
We now simply check for both version numbers.
=> pt-slave-restart now checks for MariaDB version

bin/pt-show-grants, t/pt-show-grants/basics.t, t/pt-show-grants/samples/column-grants-combined.txt, t/pt-show-grants/samples/column-grants-separate-revoke.txt, t/pt-show-grants/samples/column-grants-separate.txt, t/pt-show-grants/samples/column-grants.txt
pt-show-grants column-level privileges output resulted in different sorting order between
mysql and the mysql compatible AWS Aurora.
Solution. Simply sort the columns alphabetically.
Modified a few tests to accommodate for the change.
=> pt-show-grants - order output of column privileges - lp1523730

.gitignore, bin/pt-online-schema-change, t/pt-online-schema-change/rename_self_ref_fk_constraints.t, t/pt-online-schema-change/samples/bug-1632522.sql
pt-online-schema-change fails with duplicate key in table for self-referencing FK
https://bugs.launchpad.net/percona-toolkit/+bug/1632522
=> pt-osc: Fails with duplicate key in table for self-referencing FK

sandbox/prove2junit.pl, t/pt-online-schema-change/alter_active_table.t
The are some packages in at least ubuntu distro that can parse `prove` results into `junit` format, but there's many more perl dependencies for this and I didn't test it. Also it might not be available in all distributions.
This short script should work well for us to have some normal report in jenkins for mysql related tests.
Also there's a small "fix" for alter_active_table.t test which I needed to be able to complete the whole test suite. If that fix is not appropriate let me know and I'll remove it from the PR.
One of the jenkins jobs for which I use prove2junit.pl is here:
http://jenkins.percona.com/view/PT/job/percona-toolkit-param/
Parsed test results look like this:
http://jenkins.percona.com/view/PT/job/percona-toolkit-param/16/testReport/
=> Add prove2junit.pl script to parse mysql test results into format jenkins can understand

src/go/pt-mongodb-summary/main.go
On some servers, like a mongos with config servers, this fails if session
mode is Monotonic.
On some other servers like a secondary in a replica set, this fails if the
session mode is Strong.
Added a new func to try to get this info using both modes if necessary.
=> PT-74 Fixed getSecuritySettings func

util/build-packages
As we are compiling mongo tools we couldn't add pt-mongo-* files into MANIFEST on preparation stage as these files doesn't exist. s other tools might be compiled in future the best approach is to regenerate MANIFEST before making tarball
=> We should regenerate manifets before creating tar

sandbox/servers/mariadb/10.0/my.sandbox.cnf, sandbox/servers/mariadb/10.1/my.sandbox.cnf
The error was this:
```#   Failed test 'my.sandbox.cnf doesn't differ with active config'
=> Fix in MariaDB sandbox for pt-config-diff/basics.t tests

bin/pt-stalk, lib/bash/collect.sh
Pull request for changes for LP: 1510809.
`ps` outputs will now have the following additional columns:
```    
SZ   size in physical pages of the core image of the process.
This includes text, data, and stack space.  Device mappings
are currently excluded; this is subject to change.
RSS  resident set size, the non-swapped physical memory that a
task has used (inkiloBytes).
PSR  processor that process is currently assigned to.
```
No columns were removed from the outputs. I tried that the changes were minimal, this is why I only changed `-f` for `-F`. If more information on memory usage is needed, one can check the `top` outputs from `pt-stalk`.
All tests passed:
```
All tests successful.
Files=3, Tests=42, 100 wallclock secs ( 0.07 usr  0.02 sys +  5.84 cusr 14.53 csys = 20.46 CPU) …
```
=> pt-stalk ps include memory usage outputs

src/go/mongolib/profiler/profiler.go, src/go/mongolib/profiler/profiler_test.go, src/go/mongolib/profiler/stats.go, src/go/mongolib/stats/stats.go, src/go/mongolib/stats/stats_test.go, src/go/mongolib/util/main_test.go, src/go/pt-mongodb-query-digest/main.go, src/go/pt-mongodb-summary/main_test.go
Profiler program is separated from actually calculating stats. Also encapsulating stats allows to avoid ugly `ProcessDoc(doc, stats)` that was affecting map passed by reference.
So, now we have
```go
type Stats interface {
Add(doc proto.SystemProfile) error // adds doc to collection
Queries() stats.Queries            // returns processed collection
Reset()                            // resets/deletes collection
}
```
full implementation
```go
// New creates new instance of stats with given fingerprinter
func New(fingerprinter fingerprinter.Fingerprinter) *Stats {
s := &Stats{
fingerprinter: fingerprinter,
}
s.Reset()
return s
}
// Stats is a collection of MongoDB statistics
type Stats struct {
// dependencies
fingerprinter fingerprinter.Fingerprinter
// internal
queryInfoAndCounters …
```
=> PMM-720: encapsulate stats, separate them from profiler

bin/pt-online-schema-change, t/pt-online-schema-change/no_drop_no_swap.t
Jira: https://jira.percona.com/browse/PT-132
Launchpad: https://bugs.launchpad.net/percona-toolkit/+bug/1658274
=> PT-132 pt-online-schema-change should imply --no-drop-new-table when --no-swap-tables and --no-drop-triggers used

Changelog, bin/pt-archiver, t/pt-archiver/pt-143.t, t/pt-archiver/samples/pt-143.sql
When there is a table having a key like:
PRIMARY KEY (`id`,`start`,`end`,`user_id`(13),`interval`),
DBI driver is taking (13) as part of the field name.
Fixed the way pt-archiver composes the key using DBI cols field
instead of the colnames field since the cols field has the correct
field names for the key.
=> PT-143 Fixed key handling

bin/pt-table-checksum
For RDS we use row based replication however `pt-table-checksum` wants
to enforce statement and despite passing in the
`--no-check-binlog-format` flag, it would still run it (even though the
documentation [suggests](https://www.percona.com/doc/percona-toolkit/3.0/pt-table-checksum.html#cmdoption-pt-table-checksum--[no]check-binlog-format) it shouldn't). This appears to be a bug
because there is another binlog format check that is wrapped in
`$o->get('check-binlog-format')` slightly further down.
To resolve this, I've updated the remaining binlog format check in the
same expression as the one below and it now honours the
`--no-check-binlog-format` as expected.
=> Turn off statement based binlog checks

src/go/mongolib/proto/oplog.go
https://github.com/mongodb/mongo-tools/blob/master/common/db/db.go#L83
1. Added missing oplog document fields ("ns" + "o2")
2. Moved to ordered bson.D for object and query fields (instead of bson.M - somewhere this matters).
3. Moved to descriptive struct field names. This struct doesn't seem to be used anywhere yet but let me know if this is breaking.
4. Used 'omitempty' hints to bson marshaller to remove empty fields. Not all of these fields exist in every oplog document so I believe this saves space.
=> Oplog struct update

src/go/mongolib/proto/replconfig.go
replSetGetConfig structs:
https://docs.mongodb.com/v3.2/reference/command/replSetGetConfig/
```
[tim@centos7 tmp]$ cat test.go 
package main
import (
"fmt"
"github.com/percona/percona-toolkit/src/go/mongolib/proto"
"gopkg.in/mgo.v2"
"gopkg.in/mgo.v2/bson"
)
func main() {
session, err := mgo.Dial("mongodb://localhost:27017")
if err != nil {
panic(err)
}
out := &proto.ReplicaSetConfig{}
err = session.DB("admin").Run(bson.D{{"replSetGetConfig", 1}}, out)
if err != nil {
panic(err)
}
fmt.Println(out.Config)
for _, member := range out.Config.Members {
fmt.Println(member)
}
fmt.Println(out.Config.Settings)
}
[tim@centos7 tmp]$ go run test.go 
{test1 2 [0xc420018880 0xc420018980] 0xc4200189c0}
&{0 localhost:27017 false true false 1 0xc4200260d0 0 1}
&{1 localhost:27027 false true false 1 …
```
=> Adding replSetGetConfig structs

bin/pt-online-schema-change
- renamed 'fail-on-unique-key-change' to 'check-unique-key-change' as is compatible with the other options (check-replication-filters, check-alter
- changed documentation to say that it will FORCE to abort when it detects unique index change (was avoid)
- updated explanation a bit
- formatting for perldoc & sphinx
- pt-osc does not exist, only pt-online-schema-change, don't confuse people, it's only used internally :)
- fix unique detection by adding `UNIQUE` and `UNIQUE KEY` checking
=> PT-153: pt-online-schema-change data loss when adding unique keys - review of new feature

bin/pt-online-schema-change, t/pt-online-schema-change/pt-153.t, t/pt-online-schema-change/samples/pt-153.sql
Added `--[no]fail-on-unique-key-change param`
Now pt-osc detects if the statement for the `--alter` param is trying to add an unique key.
In that case, it will show a warning message an example queries to run to detect if there are already rows already having duplicated values for the key is being added.
=> PT-153 pt-online-schema-change data loss when adding unique keys

bin/pt-online-schema-change
- typo `use_ramdom_suffix`
- removed `drop_old_triggers` reliance to drop or not drop original trigger
- fixed bug where `--no-swap-tables` removed the triggers
- duplicated the trigger when `--no-swap-tables` and `--no-drop-new-table` is specified
- fixed atomicity of the drop/create trigger by locking both tables first.
- updated readme
=> Fix several issues in pt-osc --preserve-triggers

bin/pt-table-checksum, t/pt-table-checksum/pt-173.t, t/pt-table-checksum/samples/PT-173.sql
This feature will truncate the replicate table before starting the
checksunm process. The reason for this ticket is to clean old/stale data
in the replicate table since --empty-replicate-table will only replace
data for existing tables.
=> PT-173 Added --truncate-replicate-table

bin/pt-archiver, bin/pt-duplicate-key-checker, bin/pt-find, bin/pt-heartbeat, bin/pt-index-usage, bin/pt-kill, bin/pt-online-schema-change, bin/pt-query-digest, bin/pt-table-checksum, bin/pt-table-sync, bin/pt-table-usage, lib/TableParser.pm, t/lib/TableParser.t, t/lib/samples/generated_cols.sql, t/pt-online-schema-change/pt-202.t, t/pt-online-schema-change/samples/pt-202.sql
Modified TableParser to ignore GENERATED columns from the columns list
used to construct SELECTs/INSERTs
=> PT-202 pt-online-schema-change fails with virtual columns

src/go/mongolib/profiler/profiler_test.go
Adding `defer prof.Stop()`
https://github.com/percona/percona-toolkit/blob/228d87e108e76328a7571bfcfd627b1db6ff6590/src/go/mongolib/profiler/profiler_test.go#L92
ensures iterator gets closed (`p.iterator.Close()`)
https://github.com/percona/percona-toolkit/blob/228d87e108e76328a7571bfcfd627b1db6ff6590/src/go/mongolib/profiler/profiler.go#L114-L115
before running testing expectations for `iter.EXPECT().Close()`
https://github.com/percona/percona-toolkit/blob/228d87e108e76328a7571bfcfd627b1db6ff6590/src/go/mongolib/profiler/profiler_test.go#L62
Without this sometimes expectations were tested before iterator got closed.
=> Fix expecting iter.Close()

Changelog, bin/pt-online-schema-change, t/pt-online-schema-change/pt-229.t, t/pt-online-schema-change/samples/pt-229.sql
PXC returns WSREP detected deadlock/conflict error if there are updates on the same rows on different masters at the same time.
We shouldn't abort on that error, we should retry the insert instead.
=> PT-229 Retry insert on WSRESP deadlock on PXC

bin/pt-archiver, bin/pt-config-diff, bin/pt-deadlock-logger, bin/pt-diskstats, bin/pt-duplicate-key-checker, bin/pt-find, bin/pt-fk-error-logger, bin/pt-heartbeat, bin/pt-index-usage, bin/pt-kill, bin/pt-online-schema-change, bin/pt-query-digest, bin/pt-slave-delay, bin/pt-slave-restart, bin/pt-table-checksum, bin/pt-table-sync, bin/pt-upgrade, bin/pt-variable-advisor, lib/VersionCheck.pm, t/lib/VersionCheck.t
In order to be able to count individual users for the usage stats, we need to implement UUID instead of just using `MD5(hostname)` since most servers are just `localhost` or `db1`.
Using UUID we would be able to count unique users.
=> PMM-1479 Switched to UUID for version check

Changelog, bin/pt-mysql-summary, t/pt-mysql-summary/pt-mysql-summary.t
pt-mysql-summary has broken Security section in versions bigger then 5.6
=> PT-1485 pt-mysql-summary has broken Security section in versions bigger then 5.6

bin/pt-table-sync
The documentation states that --sync-to-master or --replicate need
the `binlog_format` to be `STATEMENT`, but the code set the `binlog format`
regardless of the operation mode.
With this patch, the `binlog_format` is only set if `--sync-to-master`
or `--replicate` options have actually been supplied on the command line,
enabling a node-to-node sync without these options without the SUPER
privilege.
=> PT-1509 Only set binlog_format when necessary

Changelog, bin/pt-table-checksum
pt-table-checksum was ignoring --nocheck-binlog-format.
That was adding an extra query that was being replicated on slaves
causing delays
=> PT-1527 pt-table-checksum3.0.8 high execution time

Changelog, bin/pt-show-grants
This fix adds these improvements:
- Only used roles are being dumped.
- Do no treat roles as regular users so, using --drop won't affect roles.
- If --only=user is specified, only roles for that user will be dumped.
- Specifying --only=role,user will ignore role (as per item #2) so the
role will be dumped ONLY if it was granted to 'user'
- Added new parameter --[no]include-unused-roles
Tags: pt-show-grants
Resolves: PT-1525
See also: PT-1488
=> PT-1546 Improved MySQL 8 roles support

bin/pt-table-checksum, lib/Sandbox.pm, t/pt-table-checksum/pt-131.t, t/pt-table-checksum/samples/pt-131.sql
The use of QRT plugin to monitor the health of production worloads cause the QRT data to show massive spikes in latency, even thought the workload is relatively unaffected.
Tags: `pt-table-checksum`
See also: [PS-235](https://jira.percona.com/browse/PS-235)
=> PT-131 Disable QRT plugin in pt-table-checksum

bin/pt-mysql-summary
* PMM-2569: Fix passing CMD_MYSQL and CMD_MYSQLDUMP. Those variables were designed to pass different location of mysql client and mysqldump, however, in one place this was not used.
* Fix getting variables from MySQL on osx, integer variables were ending with `\r` (carriage return) and script was failing with e.g. `error: invalid arithmetic operator (error token is "ummary: line 2267: 1048576`.
=> PMM-2569: Fix passing CMD_MYSQL and CMD_MYSQLDUMP.

sandbox/prove2junit.pl
This is to fix catching of reasons why tests failed and better show output in jenkins.
It should look like this:
```
Standard Output
Test description: --verbose option doesn't skip dupes reporting (bug 1402730) 
Standard Error
```
=> Fix prove2junit.pl to better catch test errors for jenkins report

bin/pt-stalk
Fixed slave_status queries not running on 5.7 and also include SHOW SLAVE STATUS output on 5.7 servers.
https://jira.percona.com/browse/PT-241
https://jira.percona.com/browse/PT-242
=> Adjusted 2 issues with slave_status

docs/release_notes.rst, docs/rn.3-0-12.txt
Removed the unnecessary content from the release_notes.rst and 
ported the content from the 3.x txt files into release_notes.rst
to make the build work again.
=>  Fixed PT-1613

bin/pt-query-digest, bin/pt-upgrade, lib/GeneralLogParser.pm, t/lib/GeneralLogParser.t, t/lib/samples/genlogs/pt-1573-general-log-system.log
The regexp to process log entries was not considering timestamps in +n,
it was only considering timestamps in -n hours
=> PT-1573 Fixed General log parser regex

bin/pt-online-schema-change
Because https://bugs.mysql.com/bug.php?id=89441 pt-osc with --drop-swap
doesn't work with MySQL 8.0+ (it will be fixed in MySQL 8.0.14) but it
should work with MariaDB 10.
Fixed version comparison to include the MySQL 'flavor'.
=> PT-1638 Fixed MariaDB support

bin/pt-show-grants
Hey,
I'm migrating from MariaDB 10.0 to Percona 5.7 and found `pt-show-grants` to be problematic.
This fixes the issue and should be good for both Percona 8+ and MariaDB 10.3+
Any feedback appreciated, 
Tim.
=> Fix pt-show-grants for MariaDB

bin/pt-config-diff
This fixes bug https://jira.percona.com/browse/PT-1633
A regexp to convert numbers matches any variable ending in a number followed by character K, M, G or T, even if the variable contains other characters, fe. 'ibtmp1:12M:autoextend:max:5G'.
This fix changes the regexp so it matches only those variables that contain only a number followed by K,M,G or T
=> PT-1633 fix incorrect parsing of a variable with number + K,M,G,T

.travis.yml, Gopkg.lock, Gopkg.toml, src/go/lib/tutil/util.go, src/go/mongolib/profiler/profiler.go, src/go/mongolib/stats/stats.go, src/go/mongolib/stats/stats_test.go, src/go/mongolib/util/util.go, src/go/pt-mongodb-summary/main.go, src/go/pt-mongodb-summary/main_test.go
- Removed t.parallel from tests
- Added lock to stats  pkg
- Fixed timeout channels usage in stats pkg
- Removed non-compatible dependency (badfix/slice) and its dependencies
- Made code improvements for linter
=> PT-1706 Made mongo tools compile with Go 1.12

bin/pt-stalk
pt-stalk matches variables for 'log_error' phrases, which also
accidentaly matches log_error_verbosity.
This patches changes pattern 'log_error' to 'log_error '.
=> PT-1734: Tailing log_error in pt-stalk doesn't work

bin/pt-diskstats
kernel 4.18+ has 18 fields in /proc/diskstats
=> diskstats not working for kernel 4.18+

bin/pt-online-schema-change
The find_child_tables is a heavy call if there are a lot of tables. This should honor the `only-same-schema-fks` option.
=> Restrict the FK check if needed

bin/pt-online-schema-change, t/pt-online-schema-change/ansi_quotes.t, t/pt-online-schema-change/rename_fk_constraints.t, t/pt-online-schema-change/rename_self_ref_fk_constraints.t
If we cannot rebuild constraints due to metadata lock, now the tool  won't delete the new table nor the triggers so the old table and the new table will have the same data and since the triggers are still in place, new_table will keep getting the updates.
Also, the tool will show the commands that the user need to run manually to complete the process
=> PT-1747 Improved FK rebuild constraints

bin/pt-query-digest, bin/pt-upgrade, lib/TcpdumpParser.pm
I've fix the year 2020 problem of `pt-query-digest`.
```
pt-query-digest --type tcpdump --limit 100 $tcpdump_result
```
If we execute this command for the result of tcpdump which ran in 2020, we cannot get correct data because of the warning below:
```
Pipeline process 4 (MySQLProtocolParser) caused an error: Argument “” isn’t numeric in multiplication (*) at pt-query-digest line 4551
```
This script parses tcpdump result by `\n20`.
For example,
```
2020-01-09 12:17:18.690344 IP 10.127.88.228.52034 > 10.228.144.92.mysql: tcp 10
0x0000:  0123 4567 89ab cdef 
2020-01-09 12:17:18.690370 IP 10.228.144.92.mysql > 10.127.88.228.52034: tcp 11
0x0000:  0123 4567 89ab cdef 
```
this data is separated into 
```
2020-01-09 12:17:18.690344 IP 10.127.88.228.52034 > 10.228.144.92.mysql: tcp 10
0x0000: …
```
=> workaround for year 2020 problem

Gopkg.toml
That way pmm-agent can use 0.9.1 without breaking other users.
=> Relax github.com/pkg/errors dependency.

src/go/mongolib/proto/system.profile.go, src/go/mongolib/proto/system.profile_test.go
In order to make explain for MongoDB work, we need to remove the "$db" field from the explain command generated in proto.system.profile since it is a duplicated field that triggers a MongoDB error.
=> PMM-6256 Updated ExplainCmd for MongoDB
