bin/pt-archiver
doc clarification of the meaning of the --check-interval option in pt-archiver
=> pt-archiver doc clarification

bin/pt-mysql-summary, lib/bash/mysql_options.sh
Added POSIX compatible --ask-pass option for shell tool pt-mysql-summary
https://bugs.launchpad.net/percona-toolkit/+bug/1455486
=> pt-mysql-summary added ask-pass option

t/pt-upgrade/compare_hosts.t, t/pt-upgrade/compare_results.t, t/pt-upgrade/diff_warnings.t, t/pt-upgrade/run_time.t
Mostly removed STRICT_TRANS_TABLES mode for tests.
=> fixed pt-upgrade tests for 5.7 compatibility

bin/pt-query-digest
Minor doc bug in pt-query-digest
=> pt-query-digest-doc-bug

t/lib/MasterSlave.t
MasterSlave changed some error messages, so changed tests accordingly.
=> some error messages changed so changed tests

t/pt-table-checksum/progress.t
minor tweaks to get --progress for pt-table-checksum unit test working consistently
=> minor tweak to pt-table-checksum progress test

bin/pt-duplicate-key-checker, lib/DuplicateKeyFinder.pm, t/lib/DuplicateKeyFinder.t, t/pt-duplicate-key-checker/basics.t, t/pt-duplicate-key-checker/samples/simple_dupe_bug_1217013.txt
Sorted key output to be consistent from run to run. (fixes test fals positives). Aligned module with tool.
=> fix tests of duplicate key module and tool for consistency

bin/pt-online-schema-change
Added an empty plugin template file and also a working sample.
=> pt-osc improved plugin docs

bin/pt-upgrade, lib/GeneralLogParser.pm
Updated dependencies for all libs/progs using GeneralLogParser
=> Bug-1585412 Updated dependencies

bin/pt-query-digest, bin/pt-upgrade, lib/MySQLProtocolParser.pm
When originally moved the fix out of the pt-query-digest into
MySQLProtocolParser I made a mistake and I've introduced an error.
Fixed.
@frank-cizmich
=> Fixed error introduced in MySQLProtocolParser

t/pt-table-checksum/issue_1485195.t, t/pt-table-checksum/samples/issue_1485195.sql
Added tests for pt-table-checksum
=> Issue 1485195 pt-table-checksum should force replica table charset to utf8 Edit

bin/pt-align, bin/pt-archiver, bin/pt-config-diff, bin/pt-deadlock-logger, bin/pt-diskstats, bin/pt-duplicate-key-checker, bin/pt-fifo-split, bin/pt-find, bin/pt-fingerprint, bin/pt-fk-error-logger, bin/pt-heartbeat, bin/pt-index-usage, bin/pt-kill, bin/pt-online-schema-change, bin/pt-query-digest, bin/pt-show-grants, bin/pt-slave-delay, bin/pt-slave-find, bin/pt-slave-restart, bin/pt-table-checksum, bin/pt-table-sync, bin/pt-table-usage, bin/pt-upgrade, bin/pt-variable-advisor, bin/pt-visual-explain, lib/DSNParser.pm, lib/OptionParser.pm, t/lib/OptionParser.t
Fixed OptionParser.
Updated all modules.
=> Bug-1635734 --config does not recognize '=' as separator

bin/pt-online-schema-change, t/pt-online-schema-change/issue-1638293.t
New feature of adding the "DATA DIRECTORY" to a new table
=> issue-1638293 feature of adding the "DATA DIRECTORY" to a new table

bin/pt-online-schema-change, bin/pt-table-checksum, lib/NibbleIterator.pm, t/lib/NibbleIterator.t
New param --pause-file=<filename>
Nibble iterator will pause while that file exists
=> Added pause to NibbleIterator

bin/pt-table-checksum, lib/SchemaIterator.pm, t/lib/SchemaIterator.t, t/lib/samples/SchemaIterator/all-dbs-tbls-5.6.txt, t/lib/samples/SchemaIterator/all-dbs.txt
https://bugs.launchpad.net/percona-toolkit/+bug/1642994
mysql.gtid_execution
sys.sys_config
mysql.proc
mysql.inventory
mysql.plugin
percona.* (including checksums, dsns table)
test.*
percona_schema.*
=> Added schemas/tables to the default ignore list

Changelog, docs/release_notes.rst
Release date added to the changelog
=> Release notes for Percona Toolkit 2.2.20

CONTRIBUTE.md
Tested the steps provided, and edited them accordingly.
=> Changes in contribute guide.

bin/pt-summary
fix for https://bugs.launchpad.net/percona-toolkit/+bug/1654668
=> Fixed for THP under RHEL

bin/pt-ioprofile, bin/pt-mext, bin/pt-mysql-summary, bin/pt-pmp, bin/pt-sift, bin/pt-stalk, bin/pt-summary, lib/bash/parse_options.sh
I've updated the command line parser script.
Also these other programs were updated:
modified:   bin/pt-ioprofile
modified:   bin/pt-mext
modified:   bin/pt-mysql-summary
modified:   bin/pt-pmp
modified:   bin/pt-sift
modified:   bin/pt-stalk
modified:   bin/pt-summary
modified:   lib/bash/parse_options.sh
Launchpad: https://bugs.launchpad.net/percona-toolkit/+bug/1667947
=> PT-76 Fixed cmd line parsing for lines having #

bin/pt-online-schema-change
(cherry picked from commit 43b50f8a8cfd58b9686ac741dd60900261861def)
=> PT-126 Fix remove comments regex

bin/pt-table-sync
prevent field type 'point' to  be taken as decimal   (poINT)
=> point is not decimal

bin/pt-online-schema-change
bug that was introduced in commit 659092bc9514c114b344908ad65e0fdb3685ae39
=> bug that was introduced in commit 659092bc9514c114b344908ad65e0fdb3685ae39

src/go/mongolib/fingerprinter/figerprinter_test.go, src/go/pt-mongodb-query-digest/main.go
Fixed connection params to connect to a db using authentication
=> PT-183 pt-mongodb-query-digest fails to connect

.travis.yml, docker-compose.yml, src/go/mongolib/proto/main_test.go, src/go/mongolib/stats/stats.go, src/go/mongolib/stats/stats_test.go
Adds .travis.yml for go part of the project. It introduces matrix of MongoDB instances - you are not using such tests anywhere, but I do in one of my PRs so I've already introduced that. Let me know what you think.
=> Add .travis.yml

bin/pt-table-checksum
Added info & links regarding the use of CRC32 as the checksum algorithm.
=> PT-187 Updated documentation for pt-table-checksum

Changelog, bin/pt-stalk, lib/bash/collect.sh
This option is for RDS instances where we cannot collect other info.
=> PT-633 Added --mysql-only option to pt-stalk

bin/pt-table-checksum
On the master, binlog_format should be always STATEMENT on master
Resolves: #PT-1527
=> PT-1556 binlog_format should be STATEMENT on master

docs/rn.3-0-1.txt, docs/rn.3-0-10.txt, docs/rn.3-0-11.txt, docs/rn.3-0-2.txt, docs/rn.3-0-3.txt, docs/rn.3-0-4.txt, docs/rn.3-0-5.txt, docs/rn.3-0-6.txt, docs/rn.3-0-7.txt, docs/rn.3-0-8.txt, docs/rn.3-0-9.txt
The scope is limited to 3.0 releases
=> Change the implementation of release notes

bin/pt-stalk
Implemented --retention-size and --retention-count
=> PT-1663 pt-stalk improvements

bin/pt-archiver, bin/pt-online-schema-change, bin/pt-table-checksum, bin/pt-table-sync, lib/IndexLength.pm, lib/NibbleIterator.pm, lib/TableNibbler.pm, t/lib/NibbleIterator.t, t/lib/TableNibbler.t, t/pt-online-schema-change/basics.t, t/pt-online-schema-change/long_fk_constraints.t, t/pt-online-schema-change/pt_1757.t, t/pt-online-schema-change/rename_fk_constraints.t, t/pt-online-schema-change/samples/pt-1757.sql, t/pt-online-schema-change/sanity_checks.t
Since now NibbleIterator can fallback to nibble (from one chunk) pt-osc can nibble tables even if due to un-accurate stats, it chose one nibble as the initial nibbling method.
=> PT-1757 Implemented fallback to nibble in NibbleIterator

bin/pt-table-checksum, t/pt-table-checksum/pt-1766.t
- Fixed DIFF_ROWS calculation
- Removed unused param --force-concat-enums
=> PT-1766 Fixed DIFF_ROWS calculation

Gopkg.lock, src/go/Makefile, src/go/docker-compose.yml, src/go/internal/testutils/env.go, src/go/mongolib/util/util.go, src/go/mongolib/util/util_test.go, src/go/pt-mongodb-summary/main.go
=> PT-1822 Fixed get hostnames for standalone

bin/pt-table-checksum, bin/pt-table-sync, lib/RowChecksum.pm, lib/TableChecksum.pm
Fixes #PT-1518
Extended fix for #406
=> PT-1518 pt-table-checksum gives error CRC32
